services:
  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"

  backend:
    build: ./backend-movease
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    links:
      - redis

  frontend:
    build: ./frontend-movease
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      BACKEND_HOST: backend
      BACKEND_PORT: 8000
